apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: ingress-patch.json
    target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: currency-converter-ingress
  
  - path: deployment-patch.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: currency-converter
